### ISSUE TITLE
Office UI Fabric grid and column @include sort order impacts overall web part design

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1294]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Media query should either be sort order independent or clear guideline should be given in which order the grid columns/media query needs to be applied to the web part. Developer at least should be aware that the order in which the Office UI Fabric SASS mixin will be used direct impacts the result.

The expectation is that media queries should always have a minimum and maximum width defined,  otherwise, the correct sort order is mandatory.

In this example, the default provisioned web part was used. On this web part, there is a wrong grid column/media query sort order implemented.

#### Observed Behavior
The provisioned style sheet code with the default web part is wrong and media queries don't work properly.

```sass
// Web Part outer container class
.helloWorld {

...

  .column {
    @include ms-Grid-col;
    @include ms-lg10;
    @include ms-xl8;
    @include ms-xlPush2;
    @include ms-lgPush1;
  }

...

}
```

The @include have the wrong sort order and therefore the web part won't be rendered properly as intended. The root cause of this sort order issue is that the ms-xlPush2 (intended for extra large displays) will be overwritten by the mx-lgPush1 (intended to be used for large displays).

The following values should match together:

**Xtra Large Display Media Query: minimum width 1024 = iPad Landscape and larger **

| CSS Class Name | Value     |  Columns |
|----------|-------------:|------:|
| ms-xl8   |  66,6666666% | 8 |
| ms-xlPush2 |    16,6666666%   |  2 |
| left over | 16,66666666% | 2 |
| **Overall** | **~100%** | **12** |

**Large Display Media Query**

| CSS Class Name | Value     |  Columns |
|----------|-------------:|------:|
| ms-lg10   |  83,3333333% | 10 |
| ms-lgPush1 |    8,3333333%   |  1 |
| left over | 8,3333333% | 1 |
| **Overall** | **~100%** | **12** |

On the default web part two media queries become mixed up as shown in the following table.

**Actual Applied Grid Columns - Mixture of Large and Xtra Large**

| CSS Class Name | Value     |  Columns |
|----------|-------------:|------:|
| ms-xl8   |  66,666666% | 8 |
| ms-lgPush1 |    8,3333333%   |  1 |
| left over | 8,3333333% | 3 |
| **Overall** | **~100%** | **12** |

This cause that the web part will never be centered on the screen.
![screen shot 2018-01-30 at 14 37 35](https://user-images.githubusercontent.com/5503835/35569353-49af3930-05cc-11e8-8306-f15d074bec56.png)

The code should be fixed by using the correct order which should look like this.

```sass
.helloWorld {
...

  .column {
    @include ms-Grid-col;
    // Media queries and grid for large displays
    @include ms-lg10;
    @include ms-lgPush1;
    // Media queries and grid for xtra large displays
    @include ms-xl8;
    @include ms-xlPush2;
  }

...

}
```

This way web part gets centred on the screen and mediaqueries get applied in the correct order.
![screen shot 2018-01-30 at 14 38 05](https://user-images.githubusercontent.com/5503835/35569466-636f1d90-05cc-11e8-828b-ab7707a410a5.png)

Both Screenshots were take at 1920x1400 Resolution.

##### Why is the sort order of mixin important?

The following example illustrates why the sort order of mixin is important. The resulting code from the original code is.

```css
// Result of @include ms-xlPush2;
@media (min-width:1024px) {
  [dir=ltr] .helloWorld_22797dd8 .column_22797dd8 {
    left: 16.66667%
  }
  [dir=rtl] .helloWorld_22797dd8 .column_22797dd8 {
    right: 16.66667%
  }
}

// Result of @include ms-lPush1;
@media (min-width:640px) {
  [dir=ltr] .helloWorld_22797dd8 .column_22797dd8 {
    left: 8.33333%
  }
  [dir=rtl] .helloWorld_22797dd8 .column_22797dd8 {
    right: 8.33333%
  }
}
```

The first media query gets applied to all displays greater than 1024px and is the result of the mixin `@include ms-xlPush2`. Later this will be overwritten by another media query (the result of @include ms-lPush1) for smaller displays than 640 pixels. The missing upper limit, e.g. max-width 1023px means that this overwrites even the previously defined media query.

As a result, the content of the container will only be pushed one instead of two columns to the right on displays larger than 1024 pixel.

The CSS result of the fixed version is:

```css
// Result of @include ms-lPush1;
@media (min-width:640px) {
  [dir=ltr] .helloWorld_8f7bb260 .column_8f7bb260 {
    left: 8.33333%
  }
  [dir=rtl] .helloWorld_8f7bb260 .column_8f7bb260 {
    right: 8.33333%
  }
}

@media (min-width:1024px) {
  .helloWorld_8f7bb260 .column_8f7bb260 {
    width: 66.66666666666666%
  }
}

// Result of @include ms-xlPush2;
@media (min-width:1024px) {
  [dir=ltr] .helloWorld_8f7bb260 .column_8f7bb260 {
    left: 16.66667%
  }
  [dir=rtl] .helloWorld_8f7bb260 .column_8f7bb260 {
    right: 16.66667%
  }
}
```

For displays larger than 1024 pixel (XL) the media query don't get overwritten by the smaller (min-width: 640px) media query. Is the screen/window size smaller than 1024 pixel the browser does a fall back on the smaller media query and style definition.

With the missing minimum and maximum width, a precise sort order needs to be used to make web parts behave properly on various screen sizes.

#### Steps to Reproduce
Provision a default web part to a new SPFx project change the media queries according to the suggestion done in this issue.

In addition, the following colour values were set to make the behaviour better visible.

```css
.helloWorld {
   .row{
			background-color: #c2c2c2;
   }
   .column{
			background-color: black;
   }
}
```

In addition, the fixed solution the one used how to demonstrate the behaviour was published to [GitHub](https://github.com/StfBauer/spfx-design-problems). All the required code is stored under `src/webparts/helloWorld/`
