### ISSUE TITLE
AppCustomizer created through the tutorial does not inherit modern theme

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#2098]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Application customizer created through the [tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions) should inherit the modern theme set on the site on modern pages.

#### Observed Behavior

The tutorial uses hard-coded Office UI Fabric styles the app customizer:

```html
<div class="ms-bgColor-themeDark ms-fontColor-white ${styles.bottom}">
      <i class="ms-Icon ms-Icon--Info" aria-hidden="true"></i> ${escape(bottomString)}
</div>
```
It seems this has stopped working recently on modern pages and the app customizer does not inherit the site theme on modern pages. 
After SPFx 1.3.4 with the introduction of `sp-office-ui-fabric-core`, we have a better way to add the styles through the .scss file:

```scss
@import '~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss';

.app {
  .bottom {
      height:40px;
      text-align:center;
      line-height:2.5;
      font-weight:bold;
      display: flex;
      align-items: center;
      justify-content: center;
      background-color: $ms-color-themePrimary;
      color: $ms-color-white;
  }
}
```

```html
<div class="${styles.bottom}">
        <i class="ms-Icon ms-Icon--Info" aria-hidden="true"></i> ${escape(bottomString)}
 </div>
```
The only problem is doing it this on the app customizer gives an error on build:

```
Error: File to import not found or unreadable: node_modules/@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss.
        on line 1 of src/extensions/helloWorld/AppCustomizer.module.scss
>> @import '~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss'
```

This is because the default scaffolding created for an App Customizer is missing the sp-office-ui-fabric-core in the package.json file. Doing an `npm install @microsoft/sp-office-ui-fabric-core` fixes the issue.

So suggestion is to add sp-office-ui-fabric-core to the default package.json of an app customiser and then the tutorial can be updated to tokenize the styles through the .scss file instead of hard coding the styles.

#### Steps to Reproduce

Create and deploy an app customizer according to the [tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions) with SPFx v1.5

When added to a modern page, you will notice the app customizer fails to inherit the theme.
