### ISSUE TITLE
Theme slots SASS variables use fixed color values instead of actual theme slots.

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#5377]
## Category

- [x] Bug

## Describe the bug
Every new SPFx project gets the following SCSS import included.

```scss
@import '~office-ui-fabric-react/dist/sass/References.scss';
```

This reference.scss now do not support theme slots anymore. Instead, they use fixed colour values of an outdated blue theme.

## Steps to reproduce

The easiest way to reproduce this issue is to create a new web part project and the bug the SASS variable stored in any of the the `$ms-*` variables in the following way.

```scss
  .row {
    @include ms-Grid-row;
    @include ms-fontColor-white;
    background-color: $ms-color-themeDark;
    @debug $ms-color-themeDark;
    padding: 20px;
  }
```

The following output illustrates the value that will be compiled in the final SASS file during the build tasks:

![image](https://user-images.githubusercontent.com/5503835/75169473-e9bce300-5728-11ea-9cb1-3be78d340a20.png)

## Expected behavior

The variable should include the following value in the SASS output for example:

```scss
'[theme:themeDark, default: someDefaultColorValue]'
```

## Developer environment

SPFx 1.10.0
