### ISSUE TITLE
Full bleed web part section do not render icons

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#6102]
## Category

- [x] Bug

## Describe the bug
When a web part is deployed in the full-bleed mode the image icon for the web part won't get rendered.

![image](https://user-images.githubusercontent.com/5503835/88454612-207e5d00-ce71-11ea-8bc1-d374af87a067.png)

The image is properly references on the page and the issue is related to the CSS used there.

![image](https://user-images.githubusercontent.com/5503835/88454669-7c48e600-ce71-11ea-82e9-e631f9228288.png)

To show the image the following CSS need to be changed:

```css

/* Inline #19 | https://n8dlab001.sharepoint.com/sites/Showcase?Mode=Edit */

.image-308 {

  /** Original Values **/
  /* width: 100%; */
  /* height: 100%; */
  /* width: contain; */
  /* object-fit: contain; */
  /* position: absolute; */
  /* height: absolute; */
  /* object-fit: undefined; */
  /* position: undefined; */
  /* position: absolute; */
  /* left: 48px; */
  /* top: undefined; */
  /* transform: 48px; */
  /* transform: undefined; */

  /** Appropriate values **/
  display: block;
  opacity: 1;
  width: 48px;
  height: 48px;
  object-fit: contain;
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  width: 48px;
  height: 48px;

}
```

The changes are not perfect but at least the image renders

![image](https://user-images.githubusercontent.com/5503835/88454739-de095000-ce71-11ea-9ee9-6645b764647f.png)

## Steps to reproduce

Deploy a web part using full bleed.

## Expected behavior

Render image defined in the web parts properly.
