### ISSUE TITLE
themeProvider.tryGetTheme does not seem to work in FullPage mode (reopen)

### ISSUE THREAD

**Issue by nbelyh** [SharePoint/sp-dev-docs#6201]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

This is basically a duplicate of the issue that was closed because of inactivity. Now with a bit more details.
https://github.com/SharePoint/sp-dev-docs/issues/5075

The only missing in the original description was that the sample code is not working for app page web parts.
I.e. if a web part is placed as "single-page" web part, the provider returns "undefined" and then the callback is never called.

Important:
In the web part manifest, both `supportsFullBleed` and `supportsThemeVariants` should be set to "true". also, the 
And the web part should be placed as single-page web part ("supportedHosts": ["SharePointWebPart", "SharePointFullPage"])

Expected or Desired Behavior
The tutorial on https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds does not work in my webpart.
I expect the provider to return theme in either case, i.e. even if supportsFullBleed is set to true and the web part is the only part on the page (i.e. hosted using "SharePointFullPage")

Observed Behavior
The tryGetTheme method returns undefined:

    // If it exists, get the theme variant
    this._themeVariant = this._themeProvider.tryGetTheme();
Secondly, the themeChangedEvent is never triggered (when changing the theme in the SharePoint user interface):

    // Register a handler to be notified if the theme variant changes
    this._themeProvider.themeChangedEvent.add(this, this._handleThemeChangedEvent);

If there is a particular reason for this behavior, and this is not a bug/typo, would be happy to hear it 😃

**Comment by andrewconnell** [comment]
@StfBauer you've done more with themes than me... do you have insight on this?

**Comment by StfBauer** [comment]
@nbelyh on the themeChangedEvent - Do you expect that it fires when you change the overall theme of the page.

**Option 1:**
<img width="492" alt="image" src="https://user-images.githubusercontent.com/5503835/91435254-5646a500-e866-11ea-8901-a3483fb401a2.png">

**Or when you change it on the section background:**

<img width="420" alt="image" src="https://user-images.githubusercontent.com/5503835/91435364-7e360880-e866-11ea-987c-7b48315fc9cd.png">

**Comment by nbelyh** [comment]
I was expecting it to fire for overall theme change... Well actually in both cases 😉

Maybe there is another way to monitor theme change?

**Comment by StfBauer** [comment]
From my testing, it actually fires on both cases but the challenging part is that the whole documentation is not useful for development yet.

The whole code of the documentation only covers the fact that you can change specific colours of your web part when you do inline style and use CSS-In-JSS. Last option only a few bought in and most people don't use it because it is inefficient and comes with a performance hit. Inside Fluent UI this is also discussed if [CSS in JS in useful in future](https://github.com/microsoft/fluentui/issues/12288#issuecomment-601834743).

The whole story missing on this documentation is the part of CSS/SASS only. For this, you don't need to use this JavaScript magic (None of the JavaScript in the documentation, maybe for some Fluent UI component but doubtable).

You have to assign the correct semantic slot in your CSS. At time commenting this documentation is highly missing. I did some testing yesterday and to apply semantic slots. To make the different color sections and theming now working on existing web parts you need to change your CSS. This needs to be considered also on future implementations.

**Pre-Fluent UI Semantic slots the theming engine worked like this:**
```scss
  .button {
    // Our button
    text-decoration: none;
    height: 32px;

    // Primary Button
    min-width: 80px;
    background-color: $ms-color-themePrimary;
    border-color: $ms-color-themePrimary;

    // Basic Button
    outline: transparent;
    position: relative;
    font-family: "Segoe UI WestEuropean","Segoe UI",-apple-system,BlinkMacSystemFont,Roboto,"Helvetica Neue",sans-serif;
    -webkit-font-smoothing: antialiased;
    font-size: $ms-font-size-m;
    font-weight: $ms-font-weight-regular;
    border-width: 0;
    text-align: center;
    cursor: pointer;
    display: inline-block;
    padding: 0 16px;

    .label {
      font-weight: $ms-font-weight-semibold;
      font-size: $ms-font-size-m;
      height: 32px;
      line-height: 32px;
      margin: 0 4px;
      vertical-align: top;
      display: inline-block;
    }
  }
```

And would have been translate into this css:

```css
.themeColorTest_2b269fec .button_2b269fec {
  text-decoration: none;
  height: 32px;
  min-width: 80px;
  background-color: "[theme:themePrimary, default: #0078d4]";
  border-color: "[theme:themePrimary, default: #0078d4]";
  outline: transparent;
  position: relative;
  font-family: "Segoe UI WestEuropean", "Segoe UI", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", sans-serif;
  -webkit-font-smoothing: antialiased;
  font-size: 14px;
  font-weight: 400;
  border-width: 0;
  text-align: center;
  cursor: pointer;
  display: inline-block;
  padding: 0 16px
}

.themeColorTest_2b269fec .button_2b269fec .label_2b269fec {
  font-weight: 600;
  font-size: 14px;
  height: 32px;
  line-height: 32px;
  margin: 0 4px;
  vertical-align: top;
  display: inline-block
}
```

The only way to achieve this now even with section support is manual.

```scss
  .button {
    // Our button
    text-decoration: none;
    height: 32px;

    // Primary Button
    min-width: 80px;
    background-color: "[theme:primaryButtonBackground]";
    color: "[theme:primaryButtonText]";
    border-color: "[theme:primaryButtonBorder]";

    // Basic Button
    outline: transparent;
    position: relative;
    font-family: "Segoe UI WestEuropean","Segoe UI",-apple-system,BlinkMacSystemFont,Roboto,"Helvetica Neue",sans-serif;
    -webkit-font-smoothing: antialiased;
    font-size: $ms-font-size-m;
    font-weight: $ms-font-weight-regular;
    border-width: 0;
    text-align: center;
    cursor: pointer;
    display: inline-block;
    padding: 0 16px;

    .label {
      font-weight: $ms-font-weight-semibold;
      font-size: $ms-font-size-m;
      height: 32px;
      line-height: 32px;
      margin: 0 4px;
      vertical-align: top;
      display: inline-block;
    }
  }
```

So you have to access for example the primaryButtonBackground directly via a theme slot:

```scss
.button {
    background-color: "[theme:primaryButtonBackground]";
}
```

The key here is the `primaryButtonBackground` sadly as far as I know there are no SASS variables define for that yet.
But here are the results of those adjustments:

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/5503835/91458310-a5e89900-e885-11ea-9fa6-da9b0594078e.png">

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/5503835/91458395-c4e72b00-e885-11ea-943b-4027440f4b26.png">

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/5503835/91458450-d597a100-e885-11ea-9fd2-8db7139bd73d.png">

and a more funny result of:
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/5503835/91458546-ed6f2500-e885-11ea-9f3f-5a5a580c6310.png">

Hope this helps you in your development. Sadly haven't tested it yet in a full bleed column but for basic web part zones it works. 

So for webparts that actually used CSS you don't even need to add any JavaScript as I tested it. The only thing to set is `supportsThemeVariants: true` in the manifest.

The documentation you shared before covers I guess some small usage scenarious where all the CSS is written in JavaScript but neither for ReactJS or HTML web parts it offers a valid an valuable apporach. For Fluent UI which only provides some compontent that could be used throughout our daily development or going full in on a pre-subscribed CSS-In-JavaScript. The documented approach seems to fit perfectly.

I hope someone could review the documentation.

Thank you @nbelyh for sharing your question because it allowed me to dig deeper into that matter. Hope this helps.
