### ISSUE TITLE
A way to add global styles (stylesheets)

### ISSUE THREAD

**Issue by vvolodin** [SharePoint/sp-dev-docs#65]
I like the idea of having namespaced and typed css but I also need to include some global styles for content I'm getting using CORS from an existing system.
What is the intended way of simply adding a stylesheet file to my project/web part?

**Comment by iclanton** [comment]
Take a look at the documentation [here](https://github.com/css-modules/css-modules#usage-with-preprocessors). TL;DR - do something like this: 

```SCSS
:global .yourGlobalClassName {
  color: green;
}
```

or something like this:

```SCSS
:global {
  .yourGlobalClassName {
    color: green;
  }
}
```

We recommend this functionality is used sparingly because it's very easy to break things by unintentionally overriding a style. The reason we're using ModuleCSS is to keep components as isolated as possible.
