### ISSUE TITLE
CSS Theme tokens: Local workbench should support the default theme and the __themeState___ object

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#721]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When I create a web part in the workbench I like to use the theme tokens without specifying the default color.
Instead this definition.
```css
.row {
    background-color: "[theme:themePrimary, default:#0078d7]";
}
```
It should be only required to use:
```css
.row {
    background-color: "[theme:themePrimary]";
}
```

#### Observed Behavior
The second variant works perfectly in the Workbench on Office 365 but not in a local workbenchen because not theme is loaded by default. The local workbench should at least include the default Office UI Fabric theme. The __themeState___ object doesn't currently load a theme in the local workbench.
![screen shot 2017-07-12 at 15 39 53](https://user-images.githubusercontent.com/5503835/28120497-7cea7fba-6718-11e7-867b-18ed2b005383.png)

On the Office 365 Workbench the theme is loaded:

![screen shot 2017-07-12 at 15 41 37](https://user-images.githubusercontent.com/5503835/28120555-a640010a-6718-11e7-9cfe-39be3765149b.png)

#### Steps to Reproduce
Create a default web part and define in the css of the web part the ```.row``` element the following way.

```css
.row {
    background-color: "[theme:themePrimary]";
}
```
This will lead to the following results in the local workbench:

![screen shot 2017-07-12 at 15 44 26](https://user-images.githubusercontent.com/5503835/28120692-0832438c-6719-11e7-9c0a-e6954e76eeb9.png)

The exact same web part in the online workbench will be shown like this. Depending on the theme that has been applied to the site.

![screen shot 2017-07-12 at 15 45 42](https://user-images.githubusercontent.com/5503835/28120739-36cbc2cc-6719-11e7-9261-d6353922cb88.png)
