### ISSUE TITLE
Theme Token Variables in SASS available for any SPFX Project

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#761]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Enhancement Request
During one of my latest blog post on using [theme colors](http://www.n8d.at/blog/how-to-use-theme-colors-in-spfx-web-parts/) in SPFX Code I created a SASS file that includes all Office UI Fabric Colors as theme tokens.
It might make sense when this variable will be available by default to be used in any custom design built in SPFX. The SASS file works as far as have have tested it pretty well in the local workbench or Office 365.

This file can also be found in one of my [GISTs](https://gist.github.com/StfBauer/413781275585f2549a4b0bbe26b8be42)

**Comment by StfBauer** [comment]
Meanwhile I release and NPM Package to support theme tokens. This npm package is name 'spfx-uifabric-themes' and can be found on [npm](https://www.npmjs.com/package/spfx-uifabric-themes)

This package can be imported through the SASS @import statement

```scss
@import './node_modules/spfx-uifabric-themes/office.theme.vars';

.container {
  background-color: $ms-themePrimary;
}
```

Variable will be replace during compilation to this.

```css
.container_742604fa {
  background-color: "[theme:themePrimary, default:#0078d7]"
}
```

Have fun coding.
