### ISSUE TITLE
Custom font CSS variables is empty

### ISSUE THREAD

**Issue by rgcircum** [SharePoint/sp-dev-docs#9902]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- All latest browser
- SPFx version : 1.19.0
- Node.js : 18.x.x

### Describe the bug / error

If you choose a custom font from Font Customizer (Settings => Change the look => Font (Preview)) after validate new font and if you revert to the Default font, the new CSS Variables genrated is empty (see screenshot)

![image](https://github.com/user-attachments/assets/698f1ba1-f860-4b9f-8f62-b24bacd995bb)

### Steps to reproduce

1. Change the font (Settings => Change the look => Font (Preview))
2. Validate
3. Return to Setting and select the default font
4. Validate
5. See the CSS variables generated on browser devtools (ex: search fontFamilyCustomFont800)

### Expected behavior

Empty CSS variables should not be generated, because if they are called in a CSS, it will be considered as existing, but since it is empty, it will be Time New Roman (or the browser's default font) that will be taken into account, and not the fallback fonts defined in the CSS

**Comment by StfBauer** [comment]
@rgcircum You are correct this is from my perspective a bug that I encountered previously too. The only since SharePoint and Fluent Design as well do not have a proper font definition on the body tag, you will fallback to the browser default.

The only workaround I can think of is to set a style to the DOM element.

```js
this.domElement.style.fontFamily = 'var(--fontFamilyBase');
```

fontFamilyBase is (should) be always set and therefor it won't fallback to Times New Roman.

**Comment by rgcircum** [comment]
The problem is not with fontFamilyBase which is always generated correctly, but with custom variables added by the font override feature.

If you define a style like this (this is just an example):

```css
p {
font-family: var(--fontFamilyCustomFont800), "Segoe UI", "Segoe UI Web (West European)", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", sans-serif;
}
```
or
```css
p {
font-family: var(--fontFamilyCustomFont800, "Segoe UI", "Segoe UI Web (West European)", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", sans-serif);
}
```
If fontFamilyCustomFont800 is generated empty, it will be used in priority and will ignore the fallback

I am testing this feature that has been awaited for a long time (even if it is still in preview) by many of my customers, I am reporting bugs in case the SPFx team did not see these bugs before the GA.

I think it is not very useful since there is never any response from the MS teams ... it is hopeless.

As for this one (https://github.com/SharePoint/sp-dev-docs/issues/9830) and many others.

Thank you for answering each time, I feel less alone :D

**Comment by StfBauer** [comment]
You should define the fallback like this.

```css
p {
    font-family: var(--fontFamilyCustomFont800, --fontFamilyBase)
 }
 ```

However, since the first value then becomes invalid it the inheritance falls through up to the `<body>` tag, which in SharePoint has the browser default 'Times New Roman' define.

When you have the, always working, font family definition on the root of your web part. The inheritance goes only to the always working base font which is then Segoe UI.

You cannot solve the issue that the font family definition on your web part get's invalid but you stop the inheritance right at the root of your web part. So instead seeing Times New Roman you will see still Segoe UI.

See: https://mdn.io/font-family at the formular definition.

![image](https://github.com/user-attachments/assets/aeb483b6-ff12-4327-a622-84844e043443)
